image: ukanga/python:2.7
services:
    - ukanga/postgis
script:
    - psql -c "CREATE USER wkcdd WITH PASSWORD 'wkcdd';" -h 127.0.0.1 -U postgres postgres
    - psql -c "CREATE DATABASE wkcdd_test OWNER wkcdd;" -h 127.0.0.1 -U postgres postgres
    - pip install -r requirements.txt
    - python setup.py test
