"""alter reports model

Revision ID: 185925c4df83
Revises: 1f42c3197633
Create Date: 2014-03-20 16:53:07.104150

"""

# revision identifiers, used by Alembic.
revision = '185925c4df83'
down_revision = '1f42c3197633'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'project_code', new_column_name='code')
    op.add_column('reports', sa.Column('month', sa.Integer(), nullable=False))
    op.add_column('reports', sa.Column('period', sa.String(), nullable=False))
    op.add_column('reports', sa.Column('project_code', sa.String(), nullable=False))
    op.add_column('reports', sa.Column('quarter', sa.String(), nullable=False))
    op.add_column('reports', sa.Column('submission_time', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('reports', 'report_date')
    op.drop_column('reports', 'project_id')
    op.drop_column('reports', 'form_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('form_id', sa.VARCHAR(), nullable=False))
    op.add_column('reports', sa.Column('project_id', sa.VARCHAR(), nullable=False))
    op.add_column('reports', sa.Column('report_date', postgresql.TIMESTAMP(timezone=True), nullable=False))
    op.drop_column('reports', 'submission_time')
    op.drop_column('reports', 'quarter')
    op.drop_column('reports', 'project_code')
    op.drop_column('reports', 'period')
    op.drop_column('reports', 'month')
    op.add_column('projects', sa.Column('project_code', sa.VARCHAR(), nullable=False))
    op.drop_column('projects', 'code')
    ### end Alembic commands ###
