"""created forms table

Revision ID: 193b377a3ffc
Revises: 2683594e0607
Create Date: 2014-03-18 18:57:15.640846

"""

# revision identifiers, used by Alembic.
revision = '193b377a3ffc'
down_revision = '2683594e0607'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forms',
    sa.Column('form_id', sa.String(), nullable=False),
    sa.Column('form_name', sa.String(), nullable=False),
    sa.Column('project_type_id', sa.Integer(), nullable=False),
    sa.Column('form_data', postgresql.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_type_id'], ['project_type.id'], ),
    sa.PrimaryKeyConstraint('form_id')
    )
    op.add_column(u'projects', sa.Column('project_type_id', sa.Integer(), nullable=False))
    op.add_column(u'reports', sa.Column('form_id', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'reports', 'form_id')
    op.drop_column(u'projects', 'project_type_id')
    op.drop_table('forms')
    op.drop_table('project_type')
    ### end Alembic commands ###
