"""point to communities to location table

Revision ID: 1f42c3197633
Revises: 23e2b3cad8d
Create Date: 2014-03-19 18:17:56.564233

"""

# revision identifiers, used by Alembic.
revision = '1f42c3197633'
down_revision = '23e2b3cad8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
