"""move geolocation column to projects

Revision ID: 24aa4082042c
Revises: 501d8df1554
Create Date: 2014-03-26 10:43:35.498988

"""

# revision identifiers, used by Alembic.
revision = '24aa4082042c'
down_revision = '501d8df1554'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communities', 'geolocation')
    op.add_column('projects', sa.Column('geolocation', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'geolocation')
    op.add_column('communities', sa.Column('geolocation', sa.TEXT(), nullable=True))
    ### end Alembic commands ###
