"""Add report_type column

Revision ID: 2604c9c4a3e6
Revises: 2901181e4776
Create Date: 2014-03-25 16:40:41.242409

"""

# revision identifiers, used by Alembic.
revision = '2604c9c4a3e6'
down_revision = '2901181e4776'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports',
                  sa.Column('report_type', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'report_type')
    ### end Alembic commands ###
