"""Initial schema generation

Revision ID: 2901181e4776
Revises: None
Create Date: 2014-03-21 12:19:13.872989

"""

# revision identifiers, used by Alembic.
revision = '2901181e4776'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(), nullable=False),
    sa.Column('submission_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('report_data', postgresql.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_project_code', 'reports', ['project_code'], unique=False)
    op.create_table('form_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forms',
    sa.Column('form_id', sa.String(), nullable=False),
    sa.Column('form_name', sa.String(), nullable=False),
    sa.Column('project_type_id', sa.Integer(), nullable=False),
    sa.Column('form_type_id', sa.Integer(), nullable=False),
    sa.Column('form_data', postgresql.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['form_type_id'], ['form_types.id'], ),
    sa.ForeignKeyConstraint(['project_type_id'], ['project_type.id'], ),
    sa.PrimaryKeyConstraint('form_id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('location_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_type'], ['location_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('constituency_id', sa.Integer(), nullable=False),
    sa.Column('geolocation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['constituency_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('project_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['project_type_id'], ['project_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_code', 'projects', ['code'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_code', table_name='projects')
    op.drop_table('projects')
    op.drop_table('communities')
    op.drop_table('locations')
    op.drop_table('forms')
    op.drop_table('project_type')
    op.drop_table('form_types')
    op.drop_index('ix_reports_project_code', table_name='reports')
    op.drop_table('reports')
    op.drop_table('location_types')
    ### end Alembic commands ###
