"""Added indexes to project model

Revision ID: 354891c319c5
Revises: 156a114bf525
Create Date: 2014-06-08 11:00:54.751166

"""

# revision identifiers, used by Alembic.
revision = '354891c319c5'
down_revision = '156a114bf525'

from alembic import op


def upgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_projects_sector'), 'projects', ['sector'], unique=False)
    op.create_index(
        op.f('ix_location_type'), 'locations', ['location_type'], unique=False)
    # end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_sector'), table_name='projects')
    op.drop_index(op.f('ix_location_type'), table_name='locations')
    # end Alembic commands ###
