"""Persist project registration json

Revision ID: 46b40717ad62
Revises: 2f8b8a345065
Create Date: 2014-05-19 16:51:43.401954

"""

# revision identifiers, used by Alembic.
revision = '46b40717ad62'
down_revision = '2f8b8a345065'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_data', postgresql.JSON(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_data')
    ### end Alembic commands ###
