"""Added project.id column; indexed project.code column

Revision ID: 496aa02de47d
Revises: 185925c4df83
Create Date: 2014-03-21 11:21:42.335937

"""

# revision identifiers, used by Alembic.
revision = '496aa02de47d'
down_revision = '185925c4df83'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index('ix_projects_code', 'projects', ['code'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_code', table_name='projects')
    op.drop_column('projects', 'id')
    ### end Alembic commands ###
