"""location_type index

Revision ID: 4deb2bb4f2c2
Revises: 354891c319c5
Create Date: 2014-07-23 16:22:04.578404

"""

# revision identifiers, used by Alembic.
revision = '4deb2bb4f2c2'
down_revision = '354891c319c5'

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_locations_location_type'),
        'locations',
        ['location_type'],
        unique=False)
    op.drop_index('ix_location_type', table_name='locations')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_location_type', 'locations', ['location_type'], unique=False)
    op.drop_index(op.f('ix_locations_location_type'), table_name='locations')
    ### end Alembic commands ###
