"""add sector column in projects

Revision ID: 501d8df1554
Revises: 2901181e4776
Create Date: 2014-03-25 22:12:45.510919

"""

# revision identifiers, used by Alembic.
revision = '501d8df1554'
down_revision = '2901181e4776'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('sector', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'sector')
    ### end Alembic commands ###
