from wkcdd.libs.utils import translation_string_factory as _

XFORM_ID = '_xform_id_string'

PROJECT_NAME = 'p_name'
PROJECT_TYPE = 'projecttype'
COMMUNITY_NAME = 'county'

COUNTY = 'county_counties'
SUB_COUNTIES = 'county_sub_counties'
CONSTITUENCY = 'county_contituency'

DATE_COMPILED = 'photo_signatures/date_compiled'
GEOLOCATION = 'project_location'

DAIRY_COWS_PROJECT_REGISTRATION = 'dairy_cows_project_registration3'
DAIRY_COWS_PROJECT_CODE = 'dc_projects'
DAIRY_COWS_PROJECT_REPORT = 'dairy_cows_project_report'
DAIRY_COWS_PROJECT_REPORT_CODE = 'perfomance_summary/dc_projects'

DAIRY_GOAT_PROJECT_REGISTRATION = 'dairy_goat_project_registration'
DAIRY_GOAT_PROJECT_CODE = 'dg_projects'
DAIRY_GOAT_PROJECT_REPORT = 'dairy_goat_project_report'
DAIRY_GOAT_PROJECT_REPORT_CODE = 'perfomance_summary/dg_projects'

FIC_PROJECT_REGISTRATION = \
    'field_industrial_crops_project_registration'
FIC_PROJECT_CODE = 'fic_projects'
FIC_PROJECT_REPORT = 'field_industrial_crop_project_report'
FIC_PROJECT_REPORT_CODE = 'perfomance_summary/fic_projects'

BODABODA_PROJECT_REGISTRATION = 'bodaboda_project_registration'
BODABODA_PROJECT_CODE = 'mct_projects'
BODABODA_PROJECT_REPORT = 'bodaboda_project_report'
BODABODA_PROJECT_REPORT_CODE = 'perfomance_summary/mct_projects'

POULTRY_PROJECT_REGISTRATION = 'poultry_project_registration'
POULTRY_PROJECT_CODE = 'poultry_projects'
POULTRY_PROJECT_REPORT = 'poultry_project_report'
POULTRY_PROJECT_REPORT_CODE = 'perfomance_summary/poultry_projects'

BANANA_PROJECT_REGISTRATION = 'banana_project_registration2'
BANANA_PROJECT_CODE = 'banana_projects'
BANANA_PROJECT_REPORT = 'banana_project_report'
BANANA_PROJECT_REPORT_CODE = 'perfomance_summary/banana_projects'

CATERING_PROJECT_REGISTRATION = 'catering_project_registration'
CATERING_PROJECT_CODE = 'catering_projects'
CATERING_PROJECT_REPORT = 'catering_project_report'
CATERING_PROJECT_REPORT_CODE = 'perfomance_summary/catering_projects'

PIGGERY_PROJECT_REGISTRATION = 'piggery_project_registration'
PIGGERY_PROJECT_CODE = 'piggery_projects'
PIGGERY_PROJECT_REPORT = 'piggery_project_report'
PIGGERY_PROJECT_REPORT_CODE = 'perfomance_summary/piggery_projects'

FISH_FARMING_PROJECT_REGISTRATION = 'fish_farming_project_registration'
FISH_FARMING_PROJECT_CODE = 'ff_projects'
FISH_FARMING_PROJECT_REPORT = 'fish_farming_project_report'
FISH_FARMING_PROJECT_REPORT_CODE = 'perfomance_summary/ff_projects'

OXEN_PLOUGH_PROJECT_REGISTRATION = 'oxen_plough_project_registration'
OXEN_PLOUGH_PROJECT_CODE = 'op_projects'
OXEN_PLOUGH_PROJECT_REPORT = 'oxen_plough_project_report'
OXEN_PLOUGH_PROJECT_REPORT_CODE = 'perfomance_summary/op_projects'

TAILORING_PROJECT_REGISTRATION = 'tailoring_project_registration'
TAILORING_PROJECT_CODE = 'tailoring_projects'
TAILORING_PROJECT_REPORT = 'tailoring_project_report'
TAILORING_PROJECT_REPORT_CODE = 'perfomance_summary/bm_projects'

REPORT_SUBMISSION_TIME = '_submission_time'
REPORT_MONTH = 'perfomance_summary/month'
REPORT_QUARTER = 'perfomance_summary/quarter_year'
REPORT_PERIOD = 'perfomance_summary/year'

PROJECT_REGISTRATION_FORMS = (
    (DAIRY_GOAT_PROJECT_REGISTRATION, DAIRY_GOAT_PROJECT_CODE),
    (DAIRY_COWS_PROJECT_REGISTRATION, DAIRY_COWS_PROJECT_CODE),
    (FIC_PROJECT_REGISTRATION, FIC_PROJECT_CODE),
    (BODABODA_PROJECT_REGISTRATION, BODABODA_PROJECT_CODE),
    (POULTRY_PROJECT_REGISTRATION, POULTRY_PROJECT_CODE),
    (BANANA_PROJECT_REGISTRATION, BANANA_PROJECT_CODE),
    (CATERING_PROJECT_REGISTRATION, CATERING_PROJECT_CODE),
    (PIGGERY_PROJECT_REGISTRATION, PIGGERY_PROJECT_CODE),
    (FISH_FARMING_PROJECT_REGISTRATION, FISH_FARMING_PROJECT_CODE),
    (OXEN_PLOUGH_PROJECT_REGISTRATION, OXEN_PLOUGH_PROJECT_CODE),
    (TAILORING_PROJECT_REGISTRATION, TAILORING_PROJECT_CODE)
)

PROJECT_REPORT_FORMS = (
    (DAIRY_GOAT_PROJECT_REPORT, DAIRY_GOAT_PROJECT_REPORT_CODE),
    (DAIRY_COWS_PROJECT_REPORT, DAIRY_COWS_PROJECT_REPORT_CODE),
    (FIC_PROJECT_REPORT, FIC_PROJECT_REPORT_CODE),
    (BODABODA_PROJECT_REPORT, BODABODA_PROJECT_REPORT_CODE),
    (POULTRY_PROJECT_REPORT, POULTRY_PROJECT_REPORT_CODE),
    (BANANA_PROJECT_REPORT, BANANA_PROJECT_REPORT_CODE),
    (CATERING_PROJECT_REPORT, CATERING_PROJECT_REPORT_CODE),
    (FISH_FARMING_PROJECT_REPORT, FISH_FARMING_PROJECT_REPORT_CODE),
    (OXEN_PLOUGH_PROJECT_REPORT, OXEN_PLOUGH_PROJECT_REPORT_CODE),
    (TAILORING_PROJECT_REPORT, TAILORING_PROJECT_REPORT_CODE)
)

PERFORMANCE_INDICATORS = {
    DAIRY_GOAT_PROJECT_REPORT: (
        ('exp_contribution', 'perfomance_summary/exp_contribution'),
        ('actual_contribution', 'perfomance_summary/actual_contribution'),
        ('community_contribution',
            'perfomance_summary/community_contribution'),
        ('bucks_target', 'mproject_performance/bucks_target'),
        ('bucks_achievement', 'mproject_performance/bucks_achievement'),
        ('bucks_percentage', 'mproject_performance/bucks_percentage'),
        ('does_proceeds_target',
            'mproject_performance/does_proceeds_target'),
        ('does_proceeds_achievement',
            'mproject_performance/does_proceeds_achievement'),
        ('does_proceeds_percentage',
            'mproject_performance/does_proceeds_percentage'),
        ('dg_proceeds_target', 'mproject_performance/dg_proceeds_target'),
        ('dg_proceeds_achievement',
            'mproject_performance/dg_proceeds_achievement'),
        ('dg_proceeds_percentage',
            'mproject_performance/dg_proceeds_percentage'),
        ('kr_target', 'mproject_performance/kr_target'),
        ('kr_achievement', 'mproject_performance/kr_achievement'),
        ('kr_percentage', 'mproject_performance/kr_percentage'),
        ('db_target', ['impact_information/db_target',
                       'mproject_performance/db_target']),
        ('db_achievement', ['impact_information/db_achievement',
                            'mproject_performance/db_achievement']),
        ('db_percentage', ['impact_information/db_percentage',
                           'mproject_performance/db_percentage']),
        ('mb_target', ['impact_information/mb_target',
                       'mproject_performance/mb_target']),
        ('mb_achievement', ['impact_information/mb_achievement',
                            'mproject_performance/mb_achievement']),
        ('mb_percentage', ['impact_information/mb_percentage',
                           'mproject_performance/mb_percentage']),
        ('fb_target', ['impact_information/fb_target',
                       'mproject_performance/fb_target']),
        ('fb_achievement', ['impact_information/fb_achievement',
                            'mproject_performance/fb_achievement']),
        ('fb_percentage', ['impact_information/fb_percentage',
                           'mproject_performance/fb_percentage']),
        ('vb_target', ['impact_information/vb_target',
                       'mproject_performance/vb_target']),
        ('vb_achievement', ['impact_information/vb_achievement',
                            'mproject_performance/vb_achievement']),
        ('vb_percentage', ['impact_information/vb_percentage',
                           'mproject_performance/vb_percentage']),
        ('m_production_target', 'mproject_performance/m_production_target'),
        ('m_production_achievement',
            'mproject_performance/m_production_achievement'),
        ('m_production_percentage',
            'mproject_performance/m_production_percentage'),
        ('grp_income_target', 'mproject_performance/grp_income_target'),
        ('grp_income_achievement',
            'mproject_performance/grp_income_achievement'),
        ('grp_income_percentage',
         'mproject_performance/grp_income_percentage'),
        ('milk_bnf_sale_target', 'mproject_performance/milk_bnf_sale_target'),
        ('milk_bnf_sale_achievement',
            'mproject_performance/milk_bnf_sale_achievement'),
        ('milk_bnf_sale_percentage',
            'mproject_performance/milk_bnf_sale_percentage')
    ),
    DAIRY_COWS_PROJECT_REPORT: (
        ('exp_contribution', 'perfomance_summary/exp_contribution'),
        ('actual_contribution', 'perfomance_summary/actual_contribution'),
        ('community_contribution',
            'perfomance_summary/community_contribution'),
        ('cows_target', 'mproject_performance/cows_target'),
        ('cows_achievement', 'mproject_performance/cows_achievement'),
        ('cows_percentage', 'mproject_performance/cows_percentage'),
        ('cws_proceeds_target', 'mproject_performance/cws_proceeds_target'),
        ('cws_proceeds_achievement',
            'mproject_performance/cws_proceeds_achievement'),
        ('cws_proceeds_percentage',
            'mproject_performance/cws_proceeds_percentage'),
        ('cr_target', 'mproject_performance/cr_target'),
        ('cr_achievement', 'mproject_performance/cr_achievement'),
        ('cr_percentage', 'mproject_performance/cr_percentage'),
        ('db_target', ['impact_information/db_target',
                       'mproject_performance/db_target']),
        ('db_achievement', ['impact_information/db_achievement',
                            'mproject_performance/db_achievement']),
        ('db_percentage', ['impact_information/db_percentage',
                           'mproject_performance/db_percentage']),
        ('fb_target', ['impact_information/fb_target',
                       'mproject_performance/fb_target']),
        ('fb_achievement', ['impact_information/fb_achievement',
                            'mproject_performance/fb_achievement']),
        ('fb_percentage', ['impact_information/fb_percentage',
                           'mproject_performance/fb_percentage']),
        ('mb_target', ['impact_information/mb_target',
                       'mproject_performance/mb_target']),
        ('mb_achievement', ['impact_information/mb_achievement',
                            'mproject_performance/mb_achievement']),
        ('mb_percentage', ['impact_information/mb_percentage',
                           'mproject_performance/mb_percentage']),
        ('vb_target', ['impact_information/vb_target',
                       'mproject_performance/vb_target']),
        ('vb_achievement', ['impact_information/vb_achievement',
                            'mproject_performance/vb_achievement']),
        ('vb_percentage', ['impact_information/vb_percentage',
                           'mproject_performance/vb_percentage']),
        ('m_acquired_target', 'mproject_performance/m_acquired_target'),
        ('m_acquired_achievement',
            'mproject_performance/m_acquired_achievement'),
        ('m_acquired_percentage',
            'mproject_performance/m_acquired_percentage'),
        ('msold_bnf_target', 'mproject_performance/msold_bnf_target'),
        ('msold_bnf_achievement',
            'mproject_performance/msold_bnf_achievement'),
        ('msold_bnf_percentage', 'mproject_performance/msold_bnf_percentage'),
        ('milk_bnf_sale_target', 'impact_information/milk_bnf_sale_target'),
        ('milk_bnf_sale_achievement',
            'impact_information/milk_bnf_sale_achievement'),
        ('milk_bnf_sale_percentage',
            'impact_information/milk_bnf_sale_percentage'),
        ('ai_target', 'mproject_performance/ai_target'),
        ('ai_achievement', 'mproject_performance/ai_achievement'),
        ('ai_percentage', 'mproject_performance/ai_percentage'),
        ('milk_grp_sale_target', ['impact_information/milk_grp_sale_target',
                                  'mproject_performance/milk_grp_sale_target']
         ),
        ('milk_grp_sale_achievement',
            ['impact_information/milk_grp_sale_achievement',
             'mproject_performance/milk_grp_sale_achievement']),
        ('milk_grp_sale_percentage',
            ['impact_information/milk_grp_sale_percentage',
             'mproject_performance/milk_grp_sale_percentage'])
    ),
    FIC_PROJECT_REPORT: (
        ('exp_contribution', 'perfomance_summary/exp_contribution'),
        ('actual_contribution', 'perfomance_summary/actual_contribution'),
        ('community_contribution',
            'perfomance_summary/community_contribution'),
        ('pm_target', 'mproject_performance/pm_target'),
        ('pm_achievement', 'mproject_performance/pm_achievement'),
        ('pm_percentage', 'mproject_performance/pm_percentage'),
        ('pm_proceeds_target', 'mproject_performance/pm_proceeds_target'),
        ('pm_proceeds_achievement',
            'mproject_performance/pm_proceeds_achievement'),
        ('pm_proceeds_percentage',
            'mproject_performance/pm_proceeds_percentage'),
        ('acreage_target', 'mproject_performance/acreage_target'),
        ('acreage_achievement', 'mproject_performance/acreage_achievement'),
        ('acreage_percentage', 'mproject_performance/acreage_percentage'),
        ('acreage_bnf_target', 'mproject_performance/acreage_bnf_target'),
        ('acreage_bnf_target', 'mproject_performance/acreage_bnf_achievement'),
        ('acreage_bnf_percentage',
            'mproject_performance/acreage_bnf_percentage'),
        ('db_target', ['impact_information/db_target',
                       'mproject_performance/db_target']),
        ('db_achievement', ['impact_information/db_achievement',
                            'mproject_performance/db_achievement']),
        ('db_percentage', ['impact_information/db_percentage',
                           'mproject_performance/db_percentage']),
        ('fb_target', ['impact_information/fb_target',
                       'mproject_performance/fb_target']),
        ('fb_achievement', ['impact_information/fb_achievement',
                            'mproject_performance/fb_achievement']),
        ('fb_percentage', ['impact_information/fb_percentage',
                           'mproject_performance/fb_percentage']),
        ('mb_target', ['impact_information/mb_target',
                       'mproject_performance/mb_target']),
        ('mb_achievement', ['impact_information/mb_achievement',
                            'mproject_performance/mb_achievement']),
        ('mb_percentage', ['impact_information/mb_percentage',
                           'mproject_performance/mb_percentage']),
        ('vb_target', ['impact_information/vb_target',
                       'mproject_performance/vb_target']),
        ('vb_achievement', ['impact_information/vb_achievement',
                            'mproject_performance/vb_achievement']),
        ('vb_percentage', ['impact_information/vb_percentage',
                           'mproject_performance/vb_percentage']),
        ('crop_yield_target', 'mproject_performance/crop_yield_target'),
        ('crop_yield_achievement',
            'mproject_performance/crop_yield_achievement'),
        ('crop_yield_percentage',
            'mproject_performance/crop_yield_percentage'),
        ('grp_target', 'mproject_performance/grp_target'),
        ('grp_achievement', 'mproject_performance/grp_achievement'),
        ('grp_percentage', 'mproject_performance/grp_percentage'),
        ('bnf_income_target', 'mproject_performance/bnf_income_target'),
        ('bnf_income_achievement',
            'mproject_performance/bnf_income_achievement'),
        ('bnf_income_percentage', 'mproject_performance/bnf_income_percentage')
    ),
    BODABODA_PROJECT_REPORT: (
        ('exp_contribution', 'perfomance_summary/exp_contribution'),
        ('actual_contribution',
            'perfomance_summary/actual_contribution'),
        ('community_contribution',
            'perfomance_summary/community_contribution'),
        ('db_target', ['impact_information/db_target',
                       'mproject_performance/db_target']),
        ('db_achievement', ['impact_information/db_achievement',
                            'mproject_performance/db_achievement']),
        ('db_percentage', ['impact_information/db_percentage',
                           'mproject_performance/db_percentage']),
        ('mb_target', ['impact_information/mb_target',
                       'mproject_performance/mb_target']),
        ('mb_achievement', ['impact_information/mb_achievement',
                            'mproject_performance/mb_achievement']),
        ('mb_percentage', ['impact_information/mb_percentage',
                           'mproject_performance/mb_percentage']),
        ('fb_target', ['impact_information/fb_target',
                       'mproject_performance/fb_target']),
        ('fb_achievement', ['impact_information/fb_achievement',
                            'mproject_performance/fb_achievement']),
        ('fb_percentage', ['impact_information/fb_percentage',
                           'mproject_performance/fb_percentage']),
        ('vb_target', ['impact_information/vb_target',
                       'mproject_performance/vb_target']),
        ('vb_achievement', ['impact_information/vb_achievement',
                            'mproject_performance/vb_achievement']),
        ('vb_percentage', ['impact_information/vb_percentage',
                           'mproject_performance/vb_percentage']),
        ('mbs_target', 'mproject_performance/mbs_target'),
        ('mbs_achievement', 'mproject_performance/mbs_achievement'),
        ('mbs_percentage', 'mproject_performance/mbs_percentage'),
        ('mbs_proceeds_target', 'mproject_performance/mbs_proceeds_target'),
        ('mbs_proceeds_achievement',
            'mproject_performance/mbs_proceeds_achievement'),
        ('mbs_proceeds_percentage',
            'mproject_performance/mbs_proceeds_percentage'),
        ('grp_target', 'impact_information/grp_target'),
        ('grp_achievement', 'impact_information/grp_achievement'),
        ('grp_percentage', 'impact_information/grp_percentage'),
        ('bnf_income_target', 'impact_information/bnf_income_target'),
        ('bnf_income_achievement',
            'impact_information/bnf_income_achievement'),
        ('bnf_income_percentage', 'impact_information/bnf_income_percentage')
    ),
    POULTRY_PROJECT_REPORT: (
        ('exp_contribution',
            'perfomance_summary/exp_contribution'),
        ('actual_contribution',
            'perfomance_summary/actual_contribution'),
        ('community_contribution',
            'perfomance_summary/community_contribution'),
        ('birds_target', 'mproject_performance/birds_target'),
        ('birds_achievement', 'mproject_performance/birds_achievement'),
        ('birds_percentage', 'mproject_performance/birds_percentage'),
        ('birds_proceeds_target',
            'mproject_performance/birds_proceeds_target'),
        ('birds_proceeds_percentage',
            'mproject_performance/birds_proceeds_percentage'),
        ('birds_proceeds_achievement',
            'mproject_performance/birds_proceeds_achievement'),
        ('pu_target', 'mproject_performance/pu_target'),
        ('pu_achievement', 'mproject_performance/pu_achievement'),
        ('pu_percentage', 'mproject_performance/pu_percentage'),
        ('db_target', ['impact_information/db_target',
                       'mproject_performance/db_target']),
        ('db_achievement', ['impact_information/db_achievement',
                            'mproject_performance/db_achievement']),
        ('db_percentage', ['impact_information/db_percentage',
                           'mproject_performance/db_percentage']),
        ('mb_target', ['impact_information/mb_target',
                       'mproject_performance/mb_target']),
        ('mb_achievement', ['impact_information/mb_achievement',
                            'mproject_performance/mb_achievement']),
        ('mb_percentage', ['impact_information/mb_percentage',
                           'mproject_performance/mb_percentage']),
        ('fb_target', ['impact_information/fb_target',
                       'mproject_performance/fb_target']),
        ('fb_achievement', ['impact_information/fb_achievement',
                            'mproject_performance/fb_achievement']),
        ('fb_percentage', ['impact_information/fb_percentage',
                           'mproject_performance/fb_percentage']),
        ('vb_target', ['impact_information/vb_target',
                       'mproject_performance/vb_target']),
        ('vb_achievement', ['impact_information/vb_achievement',
                            'mproject_performance/vb_achievement']),
        ('vb_percentage', ['impact_information/vb_percentage',
                           'mproject_performance/vb_percentage']),
        ('cr_target', 'mproject_performance/cr_target'),
        ('cr_achievement', 'mproject_performance/cr_achievement'),
        ('cr_percentage', 'mproject_performance/cr_percentage'),
        ('dbirds_number', 'mproject_performance/dbirds_number'),
        ('bsold_target', 'mproject_performance/bsold_target'),
        ('bsold_achievement', 'mproject_performance/bsold_achievement'),
        ('bsold_percentage', 'mproject_performance/bsold_percentage'),
        ('eprd_target', 'mproject_performance/eprd_target'),
        ('eprd_achievement', 'mproject_performance/eprd_achievement'),
        ('eprd_percentage', 'mproject_performance/eprd_percentage'),
        ('esold_target', 'mproject_performance/esold_target'),
        ('esold_achievement', 'mproject_performance/esold_achievement'),
        ('esold_percentage', 'mproject_performance/esold_percentage'),
        ('grp_target', 'mproject_performance/grp_target'),
        ('grp_achievement', 'mproject_performance/grp_achievement'),
        ('grp_percentage', 'mproject_performance/grp_percentage'),
        ('bnf_income_target', 'mproject_performance/bnf_income_target'),
        ('bnf_income_achievement',
            'mproject_performance/bnf_income_achievement'),
        ('bnf_income_percentage', 'mproject_performance/bnf_income_percentage')
    ),
    BANANA_PROJECT_REPORT: (
        ('exp_contribution', 'perfomance_summary/exp_contribution'),
        ('actual_contribution',
            'perfomance_summary/actual_contribution'),
        ('community_contribution',
            'perfomance_summary/community_contribution'),
        ('plantlets_target', 'mproject_performance/plantlets_target'),
        ('plantlets_achievement',
            'mproject_performance/plantlets_achievement'),
        ('plantlets_percentage', 'mproject_performance/plantlets_percentage'),
        ('plantlets_proceeds_target',
            'mproject_performance/plantlets_proceeds_target'),
        ('plantlets_proceeds_achievement',
            'mproject_performance/plantlets_proceeds_achievement'),
        ('plantlets_proceeds_percentage',
            'mproject_performance/plantlets_proceeds_percentage'),
        ('acreage_target', 'mproject_performance/acreage_target'),
        ('acreage_achievement', 'mproject_performance/acreage_achievement'),
        ('acreage_percentage', 'mproject_performance/acreage_percentage'),
        ('bb_harvested_target', 'mproject_performance/bb_harvested_target'),
        ('bb_harvested_achievement',
            'mproject_performance/bb_harvested_achievement'),
        ('bb_harvested_percentage',
            'mproject_performance/bb_harvested_percentage'),
        ('db_target', ['impact_information/db_target',
                       'mproject_performance/db_target']),
        ('db_achievement', ['impact_information/db_achievement',
                            'mproject_performance/db_achievement']),
        ('db_percentage', ['impact_information/db_percentage',
                           'mproject_performance/db_percentage']),
        ('mb_target', ['impact_information/mb_target',
                       'mproject_performance/mb_target']),
        ('mb_achievement', ['impact_information/mb_achievement',
                            'mproject_performance/mb_achievement']),
        ('mb_percentage', ['impact_information/mb_percentage',
                           'mproject_performance/mb_percentage']),
        ('fb_target', ['impact_information/fb_target',
                       'mproject_performance/fb_target']),
        ('fb_achievement', ['impact_information/fb_achievement',
                            'mproject_performance/fb_achievement']),
        ('fb_percentage', ['impact_information/fb_percentage',
                           'mproject_performance/fb_percentage']),
        ('vb_target', ['impact_information/vb_target',
                       'mproject_performance/vb_target']),
        ('vb_achievement', ['impact_information/vb_achievement',
                            'mproject_performance/vb_achievement']),
        ('vb_percentage', ['impact_information/vb_percentage',
                           'mproject_performance/vb_percentage']),
        ('ssold_target', 'mproject_performance/ssold_target'),
        ('ssold_achievement', 'mproject_performance/ssold_achievement'),
        ('ssold_percentage', 'mproject_performance/ssold_percentaget'),
        ('grp_target', 'impact_information/grp_target'),
        ('grp_achievement', 'impact_information/grp_achievement'),
        ('grp_percentage', 'impact_information/grp_percentage'),
        ('bnf_income_target', 'impact_information/bnf_income_target'),
        ('bnf_income_achievement',
            'impact_information/bnf_income_achievement'),
        ('bnf_income_percentage', 'impact_information/bnf_income_percentage')
    ),
    CATERING_PROJECT_REPORT: (
        ('exp_contribution', 'perfomance_summary/exp_contribution'),
        ('actual_contribution',
            'perfomance_summary/actual_contribution'),
        ('community_contribution',
            'perfomance_summary/community_contribution'),
        ('se_pf_target', 'mproject_performance/se_pf_target'),
        ('se_pf_achievement', 'mproject_performance/se_pf_achievement'),
        ('se_pf_percentage', 'mproject_performance/se_pf_percentage'),
        ('se_proceeds_target',
            'mproject_performance/se_proceeds_target'),
        ('se_proceeds_achievement',
            'mproject_performance/se_proceeds_achievement'),
        ('se_proceeds_percentage',
            'mproject_performance/se_proceeds_percentage'),
        ('db_target', ['impact_information/db_target',
                       'mproject_performance/db_target']),
        ('db_achievement', ['impact_information/db_achievement',
                            'mproject_performance/db_achievement']),
        ('db_percentage', ['impact_information/db_percentage',
                           'mproject_performance/db_percentage']),
        ('mb_target', ['impact_information/mb_target',
                       'mproject_performance/mb_target']),
        ('mb_achievement', ['impact_information/mb_achievement',
                            'mproject_performance/mb_achievement']),
        ('mb_percentage', ['impact_information/mb_percentage',
                           'mproject_performance/mb_percentage']),
        ('fb_target', ['impact_information/fb_target',
                       'mproject_performance/fb_target']),
        ('fb_achievement', ['impact_information/fb_achievement',
                            'mproject_performance/fb_achievement']),
        ('fb_percentage', ['impact_information/fb_percentage',
                           'mproject_performance/fb_percentage']),
        ('vb_target', ['impact_information/vb_target',
                       'mproject_performance/vb_target']),
        ('vb_achievement', ['impact_information/vb_achievement',
                            'mproject_performance/vb_achievement']),
        ('vb_percentage', ['impact_information/vb_percentage',
                           'mproject_performance/vb_percentage']),
        ('grp_target', 'impact_information/grp_target'),
        ('grp_achievement', 'impact_information/grp_achievement'),
        ('grp_percentage', 'impact_information/grp_percentage'),
        ('bnf_income_target', 'impact_information/bnf_income_target'),
        ('bnf_income_achievement',
            'impact_information/bnf_income_achievement'),
        ('bnf_income_percentage', 'impact_information/bnf_income_percentage')
    ),
    PIGGERY_PROJECT_REPORT: (
        ('exp_contribution', 'perfomance_summary/exp_contribution'),
        ('actual_contribution', 'perfomance_summary/actual_contribution'),
        ('community_contribution',
            'perfomance_summary/community_contribution'),
        ('pigs_pf_target', 'mproject_performance/pigs_pf_target'),
        ('pigs_pf_achievement', 'mproject_performance/pigs_pf_achievement'),
        ('pigs_pf_percentage', 'mproject_performance/pigs_pf_percentage'),
        ('pigs_proceeds_target', 'mproject_performance/pigs_proceeds_target'),
        ('pigs_proceeds_achievement',
            'mproject_performance/pigs_proceeds_achievement'),
        ('pigs_proceeds_percentage',
            'mproject_performance/pigs_proceeds_percentage'),
        ('piglets_realized_target',
            'mproject_performance/piglets_realized_target'),
        ('piglets_realized_achievement',
            'mproject_performance/piglets_realized_achievement'),
        ('piglets_realized_percentage',
            'mproject_performance/piglets_realized_percentage'),
        ('dpigs_piglets_target', 'mproject_performance/dpigs_piglets_target'),
        ('dpigs_piglets_number', 'mproject_performance/dpigs_piglets_number'),
        ('pigs_sold_target', 'mproject_performance/pigs_sold_target'),
        ('pigs_sold_achievement',
            'mproject_performance/pigs_sold_achievement'),
        ('pigs_sold_percentage', 'mproject_performance/pigs_sold_percentage'),
        ('db_target', ['impact_information/db_target',
                       'mproject_performance/db_target']),
        ('db_achievement', ['impact_information/db_achievement',
                            'mproject_performance/db_achievement']),
        ('db_percentage', ['impact_information/db_percentage',
                           'mproject_performance/db_percentage']),
        ('mb_target', ['impact_information/mb_target',
                       'mproject_performance/mb_target']),
        ('mb_achievement', ['impact_information/mb_achievement',
                            'mproject_performance/mb_achievement']),
        ('mb_percentage', ['impact_information/mb_percentage',
                           'mproject_performance/mb_percentage']),
        ('fb_target', ['impact_information/fb_target',
                       'mproject_performance/fb_target']),
        ('fb_achievement', ['impact_information/fb_achievement',
                            'mproject_performance/fb_achievement']),
        ('fb_percentage', ['impact_information/fb_percentage',
                           'mproject_performance/fb_percentage']),
        ('vb_target', ['impact_information/vb_target',
                       'mproject_performance/vb_target']),
        ('vb_achievement', ['impact_information/vb_achievement',
                            'mproject_performance/vb_achievement']),
        ('vb_percentage', ['impact_information/vb_percentage',
                           'mproject_performance/vb_percentage']),
        ('grp_target', 'impact_information/grp_target'),
        ('grp_achievement', 'impact_information/grp_achievement'),
        ('grp_percentage', 'impact_information/grp_percentage'),
        ('bnf_income_target', 'impact_information/bnf_income_target'),
        ('bnf_income_achievement',
            'impact_information/bnf_income_achievement'),
        ('bnf_income_percentage', 'impact_information/bnf_income_percentage')
    ),
    FISH_FARMING_PROJECT_REPORT: (
        ('exp_contribution', 'perfomance_summary/exp_contribution'),
        ('actual_contribution', 'perfomance_summary/actual_contribution'),
        ('community_contribution',
            'perfomance_summary/community_contribution'),
        ('ponds_pf_target', 'mproject_performance/ponds_pf_target'),
        ('ponds_pf_achievement', 'mproject_performance/ponds_pf_achievement'),
        ('ponds_pf_percentage', 'mproject_performance/ponds_pf_percentage'),
        ('ponds_proceeds_target',
            'mproject_performance/ponds_proceeds_target'),
        ('ponds_proceeds_achievement',
            'mproject_performance/ponds_proceeds_achievement'),
        ('ponds_proceeds_percentage',
            'mproject_performance/ponds_proceeds_percentage'),
        ('fingerlings_target', 'mproject_performance/fingerlings_target'),
        ('fingerlings_achievement',
            'mproject_performance/fingerlings_achievement'),
        ('fingerlings_percentage',
            'mproject_performance/fingerlings_percentage'),
        ('fl_proceeds_target', 'mproject_performance/fl_proceeds_target'),
        ('fl_proceeds_achievement',
            'mproject_performance/fl_proceeds_achievement'),
        ('fl_proceeds_percentage',
            'mproject_performance/fl_proceeds_percentage'),
        ('fh_target', 'mproject_performance/fh_target'),
        ('fh_achievement', 'mproject_performance/fh_achievement'),
        ('fh_percentage', 'mproject_performance/fh_percentage'),
        ('fs_target', 'mproject_performance/fs_target'),
        ('fs_achievement', 'mproject_performance/fs_achievement'),
        ('fs_percentage', 'mproject_performance/fs_percentage'),
        ('db_target', 'impact_information/db_target'),
        ('db_achievement', 'impact_information/db_achievement'),
        ('db_percentage', 'impact_information/db_percentage'),
        ('mb_target', 'impact_information/mb_target'),
        ('mb_achievement', 'impact_information/mb_achievement'),
        ('mb_percentage', 'impact_information/mb_percentage'),
        ('fb_target', 'impact_information/fb_target'),
        ('fb_achievement', 'impact_information/fb_achievement'),
        ('fb_percentage', 'impact_information/fb_percentage'),
        ('vb_target', 'impact_information/vb_target'),
        ('vb_achievement', 'impact_information/vb_achievement'),
        ('vb_percentage', 'impact_information/vb_percentage'),
        ('grp_target', 'impact_information/grp_target'),
        ('grp_achievement', 'impact_information/grp_achievement'),
        ('grp_percentage', 'impact_information/grp_percentage'),
        ('bnf_income_target', 'impact_information/bnf_income_target'),
        ('bnf_income_achievement',
            'impact_information/bnf_income_achievement'),
        ('bnf_income_percentage', 'impact_information/bnf_income_percentage')
    ),
    OXEN_PLOUGH_PROJECT_REPORT: (
        ('exp_contribution',
            'perfomance_summary/exp_contribution'),
        ('actual_contribution',
            'perfomance_summary/actual_contribution'),
        ('community_contribution',
            'perfomance_summary/community_contribution'),
        ('op_target', 'mproject_performance/op_target'),
        ('op_achievement', 'mproject_performance/op_achievement'),
        ('op_percentage', 'mproject_performance/op_percentage'),
        ('op_proceeds_target', 'mproject_performance/op_proceeds_target'),
        ('op_proceeds_achievement',
            'mproject_performance/op_proceeds_achievement'),
        ('op_proceeds_percentage',
            'mproject_performance/op_proceeds_percentage'),
        ('oxen_pf_target', 'mproject_performance/oxen_pf_target'),
        ('oxen_pf_achievement', 'mproject_performance/oxen_pf_achievement'),
        ('oxen_pf_percentage', 'mproject_performance/oxen_pf_percentage'),
        ('oxen_proceeds_target', 'mproject_performance/oxen_proceeds_target'),
        ('oxen_proceeds_achievement',
            'mproject_performance/oxen_proceeds_achievement'),
        ('oxen_proceeds_percentage',
            'mproject_performance/oxen_proceeds_percentage'),
        ('acres_ploughed_target',
            'mproject_performance/acres_ploughed_target'),
        ('acres_ploughed_achievement',
            'mproject_performance/acres_ploughed_achievement'),
        ('acres_ploughed_percentage',
            'mproject_performance/acres_ploughed_percentage'),
        ('db_target', 'impact_information/db_target'),
        ('db_achievement', 'impact_information/db_achievement'),
        ('db_percentage', 'impact_information/db_percentage'),
        ('mb_target', 'impact_information/mb_target'),
        ('mb_achievement', 'impact_information/mb_achievement'),
        ('mb_percentage', 'impact_information/mb_percentage'),
        ('fb_target', 'impact_information/fb_target'),
        ('fb_achievement', 'impact_information/fb_achievement'),
        ('fb_percentage', 'impact_information/fb_percentage'),
        ('vb_target', 'impact_information/vb_target'),
        ('vb_achievement', 'impact_information/vb_achievement'),
        ('vb_percentage', 'impact_information/vb_percentage'),
        ('grp_target', 'impact_information/grp_target'),
        ('grp_achievement', 'impact_information/grp_achievement'),
        ('grp_percentage', 'impact_information/grp_percentage'),
        ('bnf_income_target', 'impact_information/bnf_income_target'),
        ('bnf_income_achievement',
            'impact_information/bnf_income_achievement'),
        ('bnf_income_percentage', 'impact_information/bnf_income_percentage')
    ),
    TAILORING_PROJECT_REPORT: (
        ('exp_contribution', 'perfomance_summary/exp_contribution'),
        ('actual_contribution',
            'perfomance_summary/actual_contribution'),
        ('community_contribution',
            'perfomance_summary/community_contribution'),
        ('tm_pf_target', 'mproject_performance/tm_pf_target'),
        ('tm_pf_achievement', 'mproject_performance/tm_pf_achievement'),
        ('tm_pf_percentage', 'mproject_performance/tm_pf_percentage'),
        ('tm_proceeds_target', 'mproject_performance/tm_proceeds_target'),
        ('tm_proceeds_achievement',
            'mproject_performance/tm_proceeds_achievement'),
        ('tm_proceeds_percentage',
            'mproject_performance/tm_proceeds_percentage'),
        ('ts_graduated_target', 'mproject_performance/ts_graduated_target'),
        ('ts_graduated_achievement',
            'mproject_performance/ts_graduated_achievement'),
        ('ts_graduated_percentage',
            'mproject_performance/ts_graduated_percentage'),
        ('ts_iprogress_target', 'mproject_performance/ts_iprogress_target'),
        ('ts_iprogress_achievement',
            'mproject_performance/ts_iprogress_achievement'),
        ('ts_iprogress_percentage',
            'mproject_performance/ts_iprogress_percentage'),
        ('db_target', 'impact_information/db_target'),
        ('db_achievement', 'impact_information/db_achievement'),
        ('db_percentage', 'impact_information/db_percentage'),
        ('mb_target', 'impact_information/mb_target'),
        ('mb_achievement', 'impact_information/mb_achievement'),
        ('mb_percentage', 'impact_information/mb_percentage'),
        ('fb_target', 'impact_information/fb_target'),
        ('fb_achievement', 'impact_information/fb_achievement'),
        ('fb_percentage', 'impact_information/fb_percentage'),
        ('vb_target', 'impact_information/vb_target'),
        ('vb_achievement', 'impact_information/vb_achievement'),
        ('vb_percentage', 'impact_information/vb_percentage'),
        ('grp_income_target', 'impact_information/grp_income_target'),
        ('grp_income_achievement',
            'impact_information/grp_income_achievement'),
        ('grp_income_percentage', 'impact_information/grp_income_percentage'),
        ('si_sale_target', 'impact_information/si_sale_target'),
        ('si_sale_achievement',
            'impact_information/si_sale_achievement'),
        ('si_sale_percentage', 'impact_information/si_sale_percentage'),
    )
}

PERFORMANCE_INDICATOR_REPORTS = {
    DAIRY_GOAT_PROJECT_REPORT: (
        (_('Community Contribution'),
            ('exp_contribution',
             'actual_contribution',
             'community_contribution')),
        (_('Local bucks acquired (project funds)'),
            ('bucks_target', 'bucks_achievement', 'bucks_percentage')),
        (_('Local does acquired (project funds)'),
            ('does_proceeds_target',
             'does_proceeds_achievement',
             'does_proceeds_percentage')),
        (_('Dairy goats acquired (contributions)'),
            ('dg_proceeds_target',
             'dg_proceeds_achievement',
             'dg_proceeds_percentage')),
        (_('Kids realised'),
            ('kr_target', 'kr_achievement', 'kr_percentage')),
        (_('Direct beneficiaries'),
            ('db_target', 'db_achievement', 'db_percentage')),
        (_('Male beneficiaries'),
            ('mb_target', 'mb_achievement', 'mb_percentage')),
        (_('Female beneficiaries'),
            ('fb_target', 'fb_achievement', 'fb_percentage')),
        (_('Vulnerable beneficiaries'),
            ('vb_target', 'vb_achievement', 'vb_percentage')),
        (_('Avg. cups of milk per goat/mo.'),
            ('m_production_target',
             'm_production_achievement',
             'm_production_percentage')),
        (_('Avg. monthly total income earned'),
            ('grp_income_target',
             'grp_income_achievement',
             'grp_income_percentage')),
        (_('Avg. income from monthly sales'),
            ('milk_bnf_sale_target',
             'milk_bnf_sale_achievement',
             'milk_bnf_sale_percentage'))
    ),
    DAIRY_COWS_PROJECT_REPORT: (
        (_('Community Contribution'),
            ('exp_contribution',
             'actual_contribution',
             'community_contribution')),
        (_('Cows acquired (project funds)'),
            ('cows_target', 'cows_achievement', 'cows_percentage')),
        (_('Cows acquired (contributions)'),
            ('cws_proceeds_target',
             'cws_proceeds_achievement',
             'cws_proceeds_percentage')),
        (_('Calves realised'),
            ('cr_target', 'cr_achievement', 'cr_percentage')),
        (_('Direct beneficiaries'),
            ('db_target', 'db_achievement', 'db_percentage')),
        (_('Male beneficiaries'),
            ('mb_target', 'mb_achievement', 'mb_percentage')),
        (_('Female beneficiaries'),
            ('fb_target', 'fb_achievement', 'fb_percentage')),
        (_('Vulnerable beneficiaries'),
            ('vb_target', 'vb_achievement', 'vb_percentage')),
        (_('Avg. milk per beneficiary (l/mo)'),
            ('m_acquired_target',
             'm_acquired_achievement',
             'm_acquired_percentage')),
        (_('Avg. milk sold per beneficiary (l/mo)'),
            ('msold_bnf_target',
             'msold_bnf_achievement',
             'msold_bnf_percentage')),
        (_('Avg. income/beneficiary '),
            ('milk_bnf_sale_target',
             'milk_bnf_sale_achievement',
             'milk_bnf_sale_percentage')),
        (_('AI services done'),
            ('ai_target', 'ai_achievement', 'ai_percentage')),
        (_('Avg. income/group'),
            ('milk_grp_sale_target',
             'milk_grp_sale_achievement',
             'milk_grp_sale_percentage'))
    ),
    FIC_PROJECT_REPORT: (
        (_('Community Contribution'),
            ('exp_contribution',
             'actual_contribution',
             'community_contribution')),
        (_('Qty. planting materials acquired (project funds)'),
            ('pm_target', 'pm_achievement', 'pm_percentage')),
        (_('Qty. planting materials acquired (proceeds)'),
            ('pm_proceeds_target',
             'pm_proceeds_achievement',
             'pm_proceeds_percentage')),
        (_('Crop Acreage'),
            ('acreage_target', 'acreage_achievement', 'acreage_percentage')),
        (_('Crop Acreage per beneficiary'),
            ('acreage_bnf_target',
             'acreage_bnf_achievement',
             'acreage_bnf_percentage')),
        (_('Direct beneficiaries'),
            ('db_target', 'db_achievement', 'db_percentage')),
        (_('Male beneficiaries'),
            ('mb_target', 'mb_achievement', 'mb_percentage')),
        (_('Female beneficiaries'),
            ('fb_target', 'fb_achievement', 'fb_percentage')),
        (_('Vulnerable beneficiaries'),
            ('vb_target', 'vb_achievement', 'vb_percentage')),
        (_('Crop yield/acre'),
            ('crop_yield_target',
             'crop_yield_achievement',
             'crop_yield_percentage')),
        (_('Avg. income/group'),
            ('grp_target', 'grp_achievement', 'grp_percentage')),
        (_('Avg. income/beneficiary'),
            ('bnf_income_target',
             'bnf_income_achievement',
             'bnf_income_percentage'))
    ),
    BODABODA_PROJECT_REPORT: (
        (_('Community Contribution'),
            ('exp_contribution',
             'actual_contribution',
             'community_contribution')),
        (_('Bikes acquired (project funds)'),
            ('mbs_target',
             'mbs_achievement',
             'mbs_percentage')),
        (_('Bikes acquired (contributions)'),
            ('mbs_proceeds_target',
             'mbs_proceeds_achievement',
             'mbs_proceeds_percentage')),
        (_('Total Direct beneficiaries'),
            ('db_target',
             'db_achievement',
             'db_percentage')),
        (_('Female beneficiaries'),
            ('fb_target',
             'fb_achievement',
             'fb_percentage')),
        (_('Male beneficiaries'),
            ('mb_target',
             'mb_achievement',
             'mb_percentage')),
        (_('Vulnerable beneficiaries'),
            ('vb_target',
             'vb_achievement',
             'vb_percentage')),
        (_('Avg. income/group'),
            ('grp_target',
             'grp_achievement',
             'grp_percentage')),
        (_('Avg. income/beneficiary'),
            ('bnf_income_target',
             'bnf_income_achievement',
             'bnf_income_percentage')),
    ),
    POULTRY_PROJECT_REPORT: (
        (_('Community Contribution'),
            ('exp_contribution',
             'actual_contribution',
             'community_contribution')),
        (_('Birds acquired (project funds)'),
            ('birds_target',
             'birds_achievement',
             'birds_percentage')),
        (_('Birds acquired (contributions)'),
            ('birds_proceeds_target',
             'birds_proceeds_achievement',
             'birds_proceeds_percentage')),
        (_('Poultry units constructed'),
            ('pu_target',
             'pu_achievement',
             'pu_percentage')),
        (_('Direct beneficiaries'),
            ('db_target',
             'db_achievement',
             'db_percentage')),
        (_('Male beneficiaries'),
            ('mb_target',
             'mb_achievement',
             'mb_percentage')),
        (_('Female beneficiaries'),
            ('fb_target',
             'fb_achievement',
             'fb_percentage')),
        (_('Vulnerable beneficiaries'),
            ('vb_target',
             'vb_achievement',
             'vb_percentage')),
        (_('Chicks realized'),
            ('cr_target',
             'cr_achievement',
             'cr_percentage')),
        (_('Dead birds'),
            ('',
             'dbirds_#',
             '')),
        (_('Birds sold'),
            ('bsold_target',
             'bsold_achievement',
             'bsold_percentage')),
        (_('Avg. eggs produced per month'),
            ('eprd_target',
             'eprd_achievement',
             'eprd_percentage')),
        (_('Avg. eggs sold monthly'),
            ('esold_target',
             'esold_achievement',
             'esold_percentage')),
        (_('Avg. income/group'),
            ('grp_target',
             'grp_achievement',
             'grp_percentage')),
        (_('Avg. income/beneficiary'),
            ('bnf_income_target',
             'bnf_income_achievement',
             'bnf_income_percentage')),
    ),
    BANANA_PROJECT_REPORT: (
        (_('Community Contribution'),
            ('exp_contribution',
             'actual_contribution',
             'community_contribution')),
        (_('Plantlets acquired (project funds)'),
            ('plantlets_target',
             'plantlets_achievement',
             'plantlets_percentage')),
        (_('Plantlets acquired using \
            proceeds and other contributions'),
            ('plantlets_proceeds_target',
             'plantlets_proceeds_achievement',
             'plantlets_proceeds_percentage')),
        (_('Acreage under Tissue Culture Bananas'),
            ('acreage_target',
             'acreage_achievement',
             'acreage_percentage')),
        (_('Bananas harvested'),
            ('bb_harvested_target',
             'bb_harvested_achievement',
             'bb_harvested_percentage')),
        (_('Direct beneficiaries'),
            ('db_target',
             'db_achievement',
             'db_percentage')),
        (_('Male beneficiaries'),
            ('mb_target',
             'mb_achievement',
             'mb_percentage')),
        (_('Female beneficiaries'),
            ('fb_target',
             'fb_achievement',
             'fb_percentage')),
        (_('Vulnerable beneficiaries'),
            ('vb_target',
             'vb_achievement',
             'vb_percentage')),
        (_('Suckers sold'),
            ('ssold_target',
             'ssold_achievement',
             'ssold_percentage')),
        (_('Avg. income/group'),
            ('grp_target',
             'grp_achievement',
             'grp_percentage')),
        (_('Avg. income/beneficiary'),
            ('bnf_income_target',
             'bnf_income_achievement',
             'bnf_income_percentage')),
    ),
    CATERING_PROJECT_REPORT: (
        (_('Community Contribution'),
            ('exp_contribution',
             'actual_contribution',
             'community_contribution')),
        (_('Equipments acquired (project funds)'),
            ('se_pf_target',
             'se_pf_achievement',
             'se_pf_percentage')),
        (_('Equipments acquired (contributions)'),
            ('se_proceeds_target',
             'se_proceeds_achievement',
             'se_proceeds_percentage')),
        (_('Direct beneficiaries'),
            ('db_target',
             'db_achievement',
             'db_percentage')),
        (_('Male beneficiaries'),
            ('mb_target',
             'mb_achievement',
             'mb_percentage')),
        (_('Female beneficiaries'),
            ('fb_target',
             'fb_achievement',
             'fb_percentage')),
        (_('Vulnerable beneficiaries'),
            ('vb_target',
             'vb_achievement',
             'vb_percentage')),
        (_('Avg. income/group'),
            ('grp_target',
             'grp_achievement',
             'grp_percentage')),
        (_('Avg. income/beneficiary'),
            ('bnf_income_target',
             'bnf_income_achievement',
             'bnf_income_percentage')),
    ),
    PIGGERY_PROJECT_REPORT: (
        (_('Community Contribution'),
            ('exp_contribution',
             'actual_contribution',
             'community_contribution')),
        (_('Pigs acquired (project funds)'),
            ('pigs_pf_target',
             'pigs_pf_achievement',
             'pigs_pf_percentage')),
        (_('Pigs acquired (contributions)'),
            ('pigs_proceeds_target',
             'pigs_proceeds_achievement',
             'pigs_proceeds_percentage')),
        (_('Piglets realized'),
            ('piglets_realized_target',
             'piglets_realized_achievement',
             'piglets_realized_percentage')),
        (_('Pigs+Piglets lost through death'),
            ('dpigs_piglets_target', '', '')),
        (_('Pigs sold'),
            ('pigs_sold_target',
             'pigs_sold_achievement',
             'pigs_sold_percentage')),
        (_('Direct beneficiaries'),
            ('db_target',
             'db_achievement',
             'db_percentage')),
        (_('Male beneficiaries'),
            ('mb_target',
             'mb_achievement',
             'mb_percentage')),
        (_('Female beneficiaries'),
            ('fb_target',
             'fb_achievement',
             'fb_percentage')),
        (_('Vulnerable beneficiaries'),
            ('vb_target',
             'vb_achievement',
             'vb_percentage')),
        (_('Avg. income/group'),
            ('grp_target',
             'grp_achievement',
             'grp_percentage')),
        (_('Avg. income/beneficiary'),
            ('bnf_income_target',
             'bnf_income_achievement',
             'bnf_income_percentage')),
    ),
    FISH_FARMING_PROJECT_REPORT: (
        (_('Community Contribution'),
            ('exp_contribution',
             'actual_contribution',
             'community_contribution')),
        (_('Ponds acquired (project funds)'),
            ('ponds_pf_target',
             'ponds_pf_achievement',
             'ponds_pf_percentage')),
        (_('Ponds acquired (contributions)'),
            ('ponds_proceeds_target',
             'ponds_proceeds_achievement',
             'ponds_proceeds_percentage')),
        (_('Fingerlings acquired (project funds)'),
            ('fingerlings_target',
             'fingerlings_achievement',
             'fingerlings_percentage')),
        (_('Fingerlings acquired (contributions)'),
            ('fl_proceeds_target',
             'fl_proceeds_achievement',
             'fl_proceeds_percentage')),
        (_('Fish harvested'),
            ('fh_target',
             'fh_achievement',
             'fh_percentage')),
        (_('Fish sold'),
            ('fs_target',
             'fs_achievement',
             'fs_percentage')),
        (_('Direct beneficiaries'),
            ('db_target',
             'db_achievement',
             'db_percentage')),
        (_('Male beneficiaries'),
            ('mb_target',
             'mb_achievement',
             'mb_percentage')),
        (_('Female beneficiaries'),
            ('fb_target',
             'fb_achievement',
             'fb_percentage')),
        (_('Vulnerable beneficiaries'),
            ('vb_target',
             'vb_achievement',
             'vb_percentage')),
        (_('Avg. income/group'),
            ('grp_target',
             'grp_achievement',
             'grp_percentage')),
        (_('Avg. income/beneficiary'),
            ('bnf_income_target',
             'bnf_income_achievement',
             'bnf_income_percentage')),
    ),
    OXEN_PLOUGH_PROJECT_REPORT: (
        (_('Community Contribution'),
            ('exp_contribution',
             'actual_contribution',
             'community_contribution')),
        (_('Oxen ploughs acquired (project funds)'),
            ('op_target',
             'op_achievement',
             'op_percentage')),
        (_('Oxen ploughs acquired (contributions)'),
            ('op_proceeds_target',
             'op_proceeds_achievement',
             'op_proceeds_percentage')),
        (_('Oxen acquired (project funds)'),
            ('oxen_pf_target',
             'oxen_pf_achievement',
             'oxen_pf_percentage')),
        (_('Oxen acquired (contributions)'),
            ('oxen_proceeds_target',
             'oxen_proceeds_achievement',
             'oxen_proceeds_percentage')),
        (_('Acres ploughed per season'),
            ('acres_ploughed_target',
             'acres_ploughed_achievement',
             'acres_ploughed_percentage')),
        (_('Direct beneficiaries'),
            ('db_target',
             'db_achievement',
             'db_percentage')),
        (_('Female beneficiaries'),
            ('fb_target',
             'fb_achievement',
             'fb_percentage')),
        (_('Male beneficiaries'),
            ('mb_target',
             'mb_achievement',
             'mb_percentage')),
        (_('Vulnerable beneficiaries'),
            ('vb_target',
             'vb_achievement',
             'vb_percentage')),
        (_('Avg. income/group'),
            ('grp_target',
             'grp_achievement',
             'grp_percentage')),
        (_('Avg. income/beneficiary'),
            ('bnf_income_target',
             'bnf_income_achievement',
             'bnf_income_percentage')),
    ),
    TAILORING_PROJECT_REPORT: (
        (_('Community Contribution'),
            ('exp_contribution',
             'actual_contribution',
             'community_contribution')),
        (_('Tailoring machines acquired (project funds)'),
            ('tm_pf_target',
             'tm_pf_achievement',
             'tm_pf_percentage')),
        (_('Tailoring machines acquired (contributions)'),
            ('tm_proceeds_target',
             'tm_proceeds_achievement',
             'tm_proceeds_percentage')),
        (_('Tailoring students graduated'),
            ('ts_graduated_target',
             'ts_graduated_achievement',
             'ts_graduated_percentage')),
        (_('Tailoring students in progress'),
            ('ts_iprogress_target',
             'ts_iprogress_achievement',
             'ts_iprogress_percentage')),
        (_('Direct beneficiaries'),
            ('db_target',
             'db_achievement',
             'db_percentage')),
        (_('Female beneficiaries'),
            ('fb_target',
             'fb_achievement',
             'fb_percentage')),
        (_('Male beneficiaries'),
            ('mb_target',
             'mb_achievement',
             'mb_percentage')),
        (_('Vulnerable beneficiaries'),
            ('vb_target',
             'vb_achievement',
             'vb_percentage')),
        (_('Avg. income/group'),
            ('grp_income_target',
             'grp_income_achievement',
             'grp_income_percentage')),
        (_('Avg. income/beneficiary'),
            ('si_sale_target',
             'si_sale_achievement',
             'si_sale_percentage')),
    )
}
IMPACT_INDICATOR_KEYS = (
    ('no_of_b_increased_income', 'impact_information/b_income'),
    ('no_of_b_improved_houses', 'impact_information/b_improved_houses'),
    ('no_of_b_hh_assets', 'impact_information/b_hh_assets'),
    ('no_of_children', 'impact_information/no_children')
)

IMPACT_INDICATOR_REPORT = (
    (_('Beneficiaries with increased income'), 'no_of_b_increased_income'),
    (_('Beneficiaries with improved houses'), 'no_of_b_improved_houses'),
    (_('Beneficiaries with increased household assets'),
     'no_of_b_hh_assets'),
    (_('Children in schools and other learning institutions'),
     'no_of_children')
)

PROJECT_TYPE_MAPPING = [
    (DAIRY_GOAT_PROJECT_REGISTRATION, DAIRY_GOAT_PROJECT_REPORT,
     _("Dairy Goat")),
    (DAIRY_COWS_PROJECT_REGISTRATION, DAIRY_COWS_PROJECT_REPORT,
     _("Dairy Cows")),
    (FIC_PROJECT_REGISTRATION, FIC_PROJECT_REPORT,
     _("Field Industrial Crops")),
    (BODABODA_PROJECT_REGISTRATION, BODABODA_PROJECT_REPORT,
     _("Motor Cycle")),
    (POULTRY_PROJECT_REGISTRATION, POULTRY_PROJECT_REPORT,
     _("Poultry")),
    (BANANA_PROJECT_REGISTRATION, BANANA_PROJECT_REPORT,
     _("Banana")),
    (CATERING_PROJECT_REGISTRATION, CATERING_PROJECT_REPORT,
     _("Catering")),
    (PIGGERY_PROJECT_REGISTRATION, PIGGERY_PROJECT_REPORT,
     _("Piggery")),
    (FISH_FARMING_PROJECT_REGISTRATION, FISH_FARMING_PROJECT_REPORT,
     _("Fish Farming")),
    (OXEN_PLOUGH_PROJECT_REGISTRATION, OXEN_PLOUGH_PROJECT_REPORT,
     _("Oxen Plough")),
    (TAILORING_PROJECT_REGISTRATION, TAILORING_PROJECT_REPORT,
     _("Tailoring")),
]
